version: 2.1

executors:
  android-executor:
    machine:
      enabled: true

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Update Package List and Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk wget unzip
      - run:
          name: Install Android SDK Command Line Tools
          command: |
            mkdir -p $HOME/android-sdk/cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip || { echo "Failed to download command line tools"; exit 1; }
            unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools || { echo "Failed to unzip command line tools"; exit 1; }
            mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest || { echo "Failed to move command line tools"; exit 1; }
            echo y | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --update || { echo "Failed to update SDK manager"; exit 1; }
            echo y | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-21" "build-tools;34.0.0" || { echo "Failed to install SDK components"; exit 1; }
            echo y | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || { echo "Failed to accept licenses"; exit 1; }
      - run:
          name: Set Environment Variables
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export ANDROID_HOME=$HOME/android-sdk" >> $BASH_ENV
            echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Make Gradlew Executable
          command: chmod +x ./gradlew
      - run:
          name: Create local.properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Build APK
          command: ./gradlew assembleRelease || { echo "Build failed"; exit 1; }
      - run:
          name: Run Tests
          command: ./gradlew test || { echo "Tests failed"; exit 1; }
      - run:
          name: List Build Outputs
          command: ls -R app/build/outputs/apk/ || { echo "Failed to list build outputs"; exit 1; }
      - run:
          name: Archive APK
          command: |
            mkdir -p $HOME/artifacts
            cp app/release/app-release.apk $HOME/artifacts/ || { echo "Failed to copy APK"; exit 1; }
      - store_artifacts:
          path: $HOME/artifacts
          destination: artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
